staging:
  dialect: postgres
  datasource: host=127.0.0.1 port=5432 user=postgres password=postgres dbname=amazon_utils
  dir: migrations
  table: migrations

production:
  dialect: postgres
  datasource: host=${POSTGRESQL_HOST} port=${POSTGRESQL_PORT} user=${POSTGRESQL_USERNAME} password=${POSTGRESQL_PASSWORD} dbname=${POSTGRESQL_DATABASE}
  dir: migrations
  table: migrations
