version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
# .goreleaser.yaml
dockers:
  # You can have multiple Docker images.
  - #
    # ID of the image, needed if you want to filter by it later on (e.g. on custom publishers).
    id: myimg
    goos: linux
    goarch: amd64
    goarm: ""
    goamd64: "v2"
    ids:
      - mybuild
      - mynfpm




    # Path to the Dockerfile (from the project root).
    #
    # Default: 'Dockerfile'
    # Templates: allowed
    dockerfile: Dockerfile

    use: docker



 


   