apiVersion: v1
kind: Secret
metadata:
    name: {{ include "go.fullname" . }}-secrets
type: Opaque
data:
    DIALECT: "{{ .Values.goStatsSettings.DIALECT | default "" | b64enc}}
    HOST: "{{ .Values.goStatsSettings.HOST | default "" | b64enc}}
    DBPORT: "{{ .Values.goStatsSettings.DBPORT | default "" | b64enc}}
    USER: "{{ .Values.goStatsSettings.USER | default "" | b64enc}}
    PASSWORD: "{{ .Values.goStatsSettings.PASSWORD | default "" | b64enc}}
