
replicaCount: 1

image:
  repository: g1ang/go-server
  tag: release
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080



livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
      initialDelaySeconds: 3
      periodSeconds: 3

readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 15
