replicaCount: 1

image:
  repository: g1ang/my_repo369
  tag: 0.2.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  HOST: "postgres-giang-postgresql.postgresql.svc.cluster.local"
  PORT: 5432
  USER: postgres
  DBNAME: postgres
  DBPASSWORD: dz1hXCSgxg

livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3