replicaCount: 1

image:
  repository: g1ang/my_repo369
  tag: latest7
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  HOST: "10.244.0.8"
  PORT: 5432
  USER: postgres
  DBNAME: postgres
  DBPASSWORD: dz1hXCSgxg
