replicaCount: 1

image:
  repository: g1ang/my_repo369
  tag: latest2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  host: "10.244.0.8"
  dbPort: 5432
  user: postgres
  dbname: postgres
  dbpassword: dz1hXCSgxg
