name: go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: giang2002
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Go 1.22.x
      uses: actions/setup-go@v2
      with:
        go-version: "1.22.x"
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run migrations
      run: psql -f db/migrations/file_name.sql postgresql://postgres:giang2002@localhost:5432/postgres  

    - name: Build
      run: go build -v .

    - name: Test
      run: make test
      env: 
        DATABASE_DSN: "user=postgres host=localhost password=giang2002 port=5432 database=postgres sslmode=disable"

